version: '2'
services:
   keycloak:
     image: jboss/keycloak:8.0.1
     environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - KEYCLOAK_IMPORT=/importrealms/realm-test.json
     volumes:
       - ./keycloak/realm-test.json:/importrealms/realm-test.json
       - ./keycloak/medcom-vdx-theme-1.0.0.jar:/opt/jboss/keycloak/standalone/deployments/medcom-vdx-theme-1.0.0.jar
     ports:
      - "8080:8080"
   theme:
     image: kvalitetsit/keycloaktheme:latest

