version: '2'
services:
   keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    volumes:
      - ./keycloak/realm-test.json:/opt/keycloak/data/import/realm-test.json
      - ./keycloak/realm-medcom.json:/opt/keycloak/data/import/realm-medcom.json
      - ./keycloak/server-test.jks:/keystores/server-test.jks
      - ../target/medcom-vdx-keycloak-theme-1.0.0.jar:/opt/keycloak/providers/medcom-vdx-keycloak-theme-1.0.0.jar
    environment:
      - KEYCLOAK_ADMIN=keycloak
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
      - KEYCLOAK_LOG_LEVEL=ALL
    command: start-dev --http-relative-path /auth --import-realm
    ports:
      - 8080:8080
#   theme:
#     image: kvalitetsit/keycloaktheme:latest

